version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "8085:8085"
    env_file:
      - .env

  db:
    image: postgres:14
    ports:
      - "8087:5432"
    volumes:
      - ./tmp/storage/postgres:/var/lib/postgresql/data
    env_file:
      - .env


  db_console:
    image: dpage/pgadmin4:6
    ports:
      - "8097:80"
    volumes:
      - ./tmp/storage/postgres:/var/lib/postgresql/data
    env_file:
      - .env


